config/routes.rb
Bookdb::Application.routes.draw do
  match 'books', to: 'books#index', via: [:get, :post], as: "books"
  match 'book/:isbn', to: 'books#show', via: [:get], as: "book"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
require 'open-uri'

class BooksController < ApplicationController

  # GET /books
  def index
    if request.post?
      @books = ISBNdb::Query.find(:collection => 'books', :where => { params[:type].to_sym => params[:value] })
    end
  end

  # GET /books/978-0-9776-1663-3
  def show
    @book = ISBNdb::Query.find_book_by_isbn(params[:isbn])[0]
    @image = Nokogiri::HTML(open(Nokogiri::HTML(open("http://www.isbndb.com/book/#{@book.book_id}")).css("#iframeamazon")[0].attributes["src"].value)).css("img")[0].attributes["src"].value
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
<style>
  form {
    display: inline;
  }
</style>

<%= form_tag("/books", method: "post") do %>
  <%= label_tag(:value, "Search by:") %>
  <%= select_tag(:type, options_for_select([['ISBN', 'isbn'], ['Title', 'title']])) %>
  <%= text_field_tag(:value) %>
  <%= submit_tag("Search") %>
<% end %>

<% if not @books.nil? %>
<h1>Search Results</h1>

<table>
  <thead>
    <tr>
      <th>ISBN</th>
      <th>Title</th>
      <th>Author</th>
      <th>Publisher</th>
    </tr>
  </thead>

  <tbody>
    <% #while @books %>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= link_to book.isbn13, book_path(book.isbn13) %></td>
          <td><%= book.authors_text %></td>
          <td><%= book.publisher_text["__content__"] %></td>
        </tr>
      <% end %>
      <% #@books = @books.next_page %>
    <% #end %>
  </tbody>
</table>

<br>
<% end %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<img src="<%= @image %>" />
<br />
<p>ISBN: <%= @book.isbn13 %></p>
<p>Author: <%= @book.authors_name %></p>
<p>Publisher: <%= @book.publisher_text["__content__"] %></p>

<%= link_to "Back", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookdb</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>